name: go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  defaults:
    run:
      working-directory: ./src

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'src/go.mod'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
